steps:
# Steps to build a docker image for flask, push it to container registry and deploy it to cloud run.  
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/causal-ratio-405619/flask','.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/causal-ratio-405619/flask']
  
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args: ['run', 'deploy','flask', '--image','gcr.io/causal-ratio-405619/flask', '--region','us-central1', '--add-cloudsql-instances', 'causal-ratio-405619:us-central1:mypostgres','--platform','managed', '--port','8080', '--allow-unauthenticated']

images:
- gcr.io/causal-ratio-405619/flask

